set(TARGET llama-cvector-generator)
find_program(CARGO_EXECUTABLE cargo REQUIRED)

set(CVECTOR_GENERATOR_RUST_MANIFEST ${CMAKE_CURRENT_SOURCE_DIR}/../cvector-generator-rust/Cargo.toml)
set(CVECTOR_GENERATOR_RUST_TARGET_DIR ${CMAKE_BINARY_DIR}/cargo/cvector-generator)
set(CVECTOR_GENERATOR_RUST_BIN ${CVECTOR_GENERATOR_RUST_TARGET_DIR}/debug/${TARGET}${CMAKE_EXECUTABLE_SUFFIX})
set(CVECTOR_GENERATOR_RUST_OUTPUT ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${TARGET}${CMAKE_EXECUTABLE_SUFFIX})

add_custom_command(
    OUTPUT ${CVECTOR_GENERATOR_RUST_OUTPUT}
    COMMAND ${CARGO_EXECUTABLE} build --manifest-path ${CVECTOR_GENERATOR_RUST_MANIFEST} --target-dir ${CVECTOR_GENERATOR_RUST_TARGET_DIR} --bin ${TARGET}
    COMMAND ${CMAKE_COMMAND} -E copy ${CVECTOR_GENERATOR_RUST_BIN} ${CVECTOR_GENERATOR_RUST_OUTPUT}
    DEPENDS
        ${CVECTOR_GENERATOR_RUST_MANIFEST}
        ${CMAKE_CURRENT_SOURCE_DIR}/../cvector-generator-rust/src/main.rs
)
add_custom_target(${TARGET} ALL DEPENDS ${CVECTOR_GENERATOR_RUST_OUTPUT})

if(LLAMA_TOOLS_INSTALL)
    install(PROGRAMS ${CVECTOR_GENERATOR_RUST_OUTPUT} DESTINATION ${CMAKE_INSTALL_BINDIR})
endif()
