//
// MIT license
// Copyright (C) 2024 Intel Corporation
// SPDX-License-Identifier: MIT
//

//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//

#ifndef GGML_SYCL_BACKEND_HPP
#define GGML_SYCL_BACKEND_HPP

#include "binbcast-defs.inc"
#include "common-defs.inc"
#include "concat-defs.inc"
#include "conv-defs.inc"
#include "convert-defs.inc"
#include "count-equal-defs.inc"
#include "cpy-defs.inc"
#include "dequantize-defs.inc"
#include "dmmv-defs.inc"
#include "element_wise-defs.inc"
#include "fattn-defs.inc"
#include "gated_delta_net-defs.inc"
#include "gla-defs.inc"
#include "im2col-defs.inc"
#include "mmq-defs.inc"
#include "mmvq-defs.inc"
#include "norm-defs.inc"
#include "outprod-defs.inc"
#include "pad-defs.inc"
#include "pad_reflect_1d-defs.inc"
#include "quantize-defs.inc"
#include "quants-defs.inc"
#include "roll-defs.inc"
#include "rope-defs.inc"
#include "set_rows-defs.inc"
#include "ssm_conv-defs.inc"
#include "softmax-defs.inc"
#include "tsembd-defs.inc"
#include "upscale-defs.inc"
#include "wkv-defs.inc"


#endif  // GGML_SYCL_BACKEND_HPP
