use std::fs;

const HELP_START_MARKER: &str = "<!-- HELP_START -->";
const HELP_END_MARKER: &str = "<!-- HELP_END -->";
const NOTE_MESSAGE: &str =
    "<!-- IMPORTANT: The list below is auto-generated by llama-gen-docs; do NOT modify it manually -->";

const MD_FILES: &[(&str, &str)] = &[
    ("tools/cli/README.md", "CLI-specific params"),
    ("tools/completion/README.md", "Completion-specific params"),
    ("tools/server/README.md", "Server-specific params"),
];

#[derive(Clone, Copy)]
struct ArgDoc {
    args: &'static str,
    help: &'static str,
}

const COMMON_OPTIONS: &[ArgDoc] = &[
    ArgDoc {
        args: "-h, --help",
        help: "show this help message and exit",
    },
    ArgDoc {
        args: "-m, --model FNAME",
        help: "model path",
    },
    ArgDoc {
        args: "-t, --threads N",
        help: "number of threads to use during generation",
    },
    ArgDoc {
        args: "-c, --ctx-size N",
        help: "size of the prompt context",
    },
];

const SAMPLING_OPTIONS: &[ArgDoc] = &[
    ArgDoc {
        args: "-n, --predict N",
        help: "number of tokens to predict",
    },
    ArgDoc {
        args: "--temp N",
        help: "sampling temperature",
    },
    ArgDoc {
        args: "--top-k N",
        help: "top-k sampling",
    },
    ArgDoc {
        args: "--top-p N",
        help: "top-p sampling",
    },
];

const SPECIFIC_OPTIONS: &[ArgDoc] = &[
    ArgDoc {
        args: "-p, --prompt PROMPT",
        help: "prompt to start generation with",
    },
    ArgDoc {
        args: "--host HOST",
        help: "server listen address where applicable",
    },
    ArgDoc {
        args: "--port PORT",
        help: "server listen port where applicable",
    },
];

fn escape_md(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', "<br/>")
}

fn write_table(out: &mut String, rows: &[ArgDoc]) {
    out.push_str("| Argument | Explanation |\n");
    out.push_str("| -------- | ----------- |\n");
    for row in rows {
        out.push_str("| `");
        out.push_str(&escape_md(row.args));
        out.push_str("` | ");
        out.push_str(&escape_md(row.help.trim()));
        out.push_str(" |\n");
    }
}

fn build_help(specific_section_header: &str) -> String {
    let mut out = String::new();
    out.push_str(HELP_START_MARKER);
    out.push_str("\n\n");
    out.push_str(NOTE_MESSAGE);
    out.push_str("\n\n### Common params\n\n");
    write_table(&mut out, COMMON_OPTIONS);
    out.push_str("\n\n### Sampling params\n\n");
    write_table(&mut out, SAMPLING_OPTIONS);
    out.push_str("\n\n### ");
    out.push_str(specific_section_header);
    out.push_str("\n\n");
    write_table(&mut out, SPECIFIC_OPTIONS);
    out.push('\n');
    out.push_str(HELP_END_MARKER);
    out
}

fn replace_help(content: &str, new_help: &str) -> Result<String, String> {
    let help_start = content
        .find(HELP_START_MARKER)
        .ok_or_else(|| "missing help start marker".to_string())?;
    let help_end = content
        .find(HELP_END_MARKER)
        .ok_or_else(|| "missing help end marker".to_string())?;
    if help_end <= help_start {
        return Err("help end marker appears before start marker".to_string());
    }

    Ok(format!(
        "{}{}{}",
        &content[..help_start],
        new_help,
        &content[help_end + HELP_END_MARKER.len()..]
    ))
}

fn update_file(path: &str, specific_section_header: &str) -> Result<(), String> {
    let content =
        fs::read_to_string(path).map_err(|err| format!("failed to read {path}: {err}"))?;
    let new_help = build_help(specific_section_header);
    let updated = replace_help(&content, &new_help)
        .map_err(|err| format!("failed to update help in {path}: {err}"))?;
    fs::write(path, updated).map_err(|err| format!("failed to write {path}: {err}"))?;
    println!("Updated help in '{path}'");
    Ok(())
}

fn main() {
    for (path, section) in MD_FILES {
        if let Err(err) = update_file(path, section) {
            eprintln!("{err}");
            std::process::exit(1);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn markdown_escapes_pipes_and_newlines() {
        assert_eq!(escape_md("a|b\nc"), "a\\|b<br/>c");
    }

    #[test]
    fn generated_help_has_markers_and_sections() {
        let help = build_help("Server-specific params");
        assert!(help.starts_with(HELP_START_MARKER));
        assert!(help.ends_with(HELP_END_MARKER));
        assert!(help.contains("### Common params"));
        assert!(help.contains("### Sampling params"));
        assert!(help.contains("### Server-specific params"));
    }

    #[test]
    fn replaces_only_marked_region() {
        let content = format!("before\n{HELP_START_MARKER}\nold\n{HELP_END_MARKER}\nafter");
        let updated = replace_help(&content, "NEW").unwrap();
        assert_eq!(updated, "before\nNEW\nafter");
    }

    #[test]
    fn rejects_missing_markers() {
        assert!(replace_help("no markers", "NEW").is_err());
    }
}
