set(TARGET llama-convert-llama2c-to-ggml)
find_program(CARGO_EXECUTABLE cargo REQUIRED)
set(CONVERT_LLAMA2C_RUST_MANIFEST ${CMAKE_CURRENT_SOURCE_DIR}/../convert-llama2c-to-ggml-rust/Cargo.toml)
set(CONVERT_LLAMA2C_RUST_TARGET_DIR ${CMAKE_BINARY_DIR}/cargo/convert-llama2c-to-ggml)
set(CONVERT_LLAMA2C_RUST_BIN ${CONVERT_LLAMA2C_RUST_TARGET_DIR}/debug/${TARGET}${CMAKE_EXECUTABLE_SUFFIX})
set(CONVERT_LLAMA2C_RUST_OUTPUT ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${TARGET}${CMAKE_EXECUTABLE_SUFFIX})

add_custom_command(
    OUTPUT ${CONVERT_LLAMA2C_RUST_OUTPUT}
    COMMAND ${CARGO_EXECUTABLE} build --manifest-path ${CONVERT_LLAMA2C_RUST_MANIFEST} --target-dir ${CONVERT_LLAMA2C_RUST_TARGET_DIR} --bin ${TARGET}
    COMMAND ${CMAKE_COMMAND} -E copy ${CONVERT_LLAMA2C_RUST_BIN} ${CONVERT_LLAMA2C_RUST_OUTPUT}
    DEPENDS
        ${CONVERT_LLAMA2C_RUST_MANIFEST}
        ${CMAKE_CURRENT_SOURCE_DIR}/../convert-llama2c-to-ggml-rust/src/main.rs
)
add_custom_target(${TARGET} ALL DEPENDS ${CONVERT_LLAMA2C_RUST_OUTPUT})
install(PROGRAMS ${CONVERT_LLAMA2C_RUST_OUTPUT} DESTINATION ${CMAKE_INSTALL_BINDIR})
